### ISSUE TITLE
test mail working, mail from flow not working

### ISSUE THREAD

**Issue by Heki2017** [jordenc/email-sender#10]
I have installed this app, which looks very promising. However when I created my first flow with the app and run the test for the flow the waiting wheel keeps turning and no mail is received. I send a text only mail with a token (I tried several tokens). I just cannot understand why the testmail at installation works, and the mail from flow not.
![img_43bc08b7eab1-1](https://user-images.githubusercontent.com/26427299/51373698-bc702f80-1b3b-11e9-9653-a7eb83d9acc2.jpeg)

**Comment by jordenc** [comment]
Can you try without the token? Just to see if that works.

**Comment by Heki2017** [comment]
Dear Jordan, thanks for prompt reaction. I tried without the token, but the result is the same

Kind regards, Hedzer

Sent by iPhone, please ignore possible typos

**Comment by jordenc** [comment]
Sadly, there is no way for me to know what went wrong. If you can, please try to run this app as a developer (https://developer.athom.com/) and see if you can send me the logs (please make sure not to hide any usernames and passwords). You need a lot of technical knowhow for this though...

**Comment by Heki2017** [comment]
Thanks Jordan for the advice, however I am not (yet) on that level. Maybe there will be more people reporting the issue and a pattern will submerge.

I will try to find ways to test f.i. other email accounts and see if I can have different results. Will keep you posted.

Enjoy the upcoming weekend, Hedzer

**Comment by WesRos** [comment]
Hi Hedzer and Jordan,
I've the same issue in Homey firmware: 1.5.13
In the settings menu the test works, but sending e-mail in a flow doesn't.
@jordenc , your question about to run the app as developer, do I have to install your app by cli, or is it possible to catch only the logging by cli?

Edit: after a longer time, I've received the emails. When testing the flow, the process sign was present, instead of the success sign.

**Comment by jordenc** [comment]
@WesRos you need to download the app from Github, install NodeJS, install the developer tools from Athom and then run ("athom app run") the app (which also installs it, until you press CTRL-C)

**Comment by HenkVanA** [comment]
I have exactly the same issue as Heki2017 reported
Did not have the issue in the past, only since I upgraded to Homey 2.0

**Comment by joepwijers** [comment]
Same issue, on Homey 2.0
However with a slight variation:
- when sending a test mail from settings, it arrives correctly in my Inbox.
- when sending email from a flow, it arrives, but in the spam folder.

This suggests that in a flow it is not sent in exactly the same way; in a way that makes it being detected as spam.

I am using an SMTP server with credentials and the from-address is from the same email provider 

Earlier I sent it from the SMTP server of my internet provider, using the same from-address. In that case it always ends up in spam detection, which makes sense as that email is registered as related to a different SMTP server.

Possibly this is a clue: Homey might not be sending from the email address specified in the settings?

J

**Comment by jordenc** [comment]
The mail_from is set correctly. In the "test function" I set a text and a HTML version with "This is a testmail" as content.
There shouldn't be a difference between that, and manually sending a message containing the same text.

If the results differ, make sure you don't use a spamfilter and/or try running the app from CLI as a developer to see what happens (the logging will show the result)

**Comment by dannymertens** [comment]
Same issue, test mail fine, in flow nothing, even very basic mail (plain text) is not working :-(
<img width="1365" alt="mail problem" src="https://user-images.githubusercontent.com/46963011/55469100-09c15080-5605-11e9-8724-aba74e3f57fb.png">

Latest version of Homey and App, tested with Flow editor and apps on iOS, Android

**Comment by jordenc** [comment]
Can you try to run in developer mode from commandline, and see what happens if you send a mail by executing that function?

**Comment by dannymertens** [comment]
> Can you try to run in developer mode from commandline, and see what happens if you send a mail by executing that function?

Hi Jorden, thanks for the quick reply but can you give me a little more details, new in this stuff ;-)

**Comment by dannymertens** [comment]
OK heb even een test account aangemaakt op gmail, laat maar weten wat ik kan testen @jordenc 

Staat ook 2way authentificatie aan, app password gemaakt net zoals in mijn officiële account, en ook nu gaat test weer goed en in flow niet
![test mail](https://user-images.githubusercontent.com/46963011/55470372-c1eff880-5607-11e9-9655-90b14ce23856.png)

**Comment by jordenc** [comment]
There is a tutorial (including Youtube video) on https://community.athom.com/t/how-to-cli-install-method/198

**Comment by dannymertens** [comment]
@jordenc OK zo ver ben ik en wat moet ik nu doen, gewoon de flow runnen?
<img width="856" alt="app debug" src="https://user-images.githubusercontent.com/46963011/55472278-fd8cc180-560b-11e9-973e-9d88b930b725.png">

**Comment by dannymertens** [comment]
@jordenc OK just did a test again and now it works!?

Line breaks don't work but the mail is being send now, can you explain what I did different now and do I need to deinstall something again from my homey after this install? if so what and how ;-)


![image](https://user-images.githubusercontent.com/46963011/55472487-8277db00-560c-11e9-8a2f-e1b93d7dbc14.png)

**Comment by jordenc** [comment]
Probeer eens athom app run in plaats van athom app install.

Dan zie je de logs langs schieten tijdens het uitvoeren van flows. Als je dan je flow uitvoert zou je eventueel een foutmelding kunnen zien.

**Comment by dannymertens** [comment]
> Probeer eens athom app run in plaats van athom app install.
> 
> Dan zie je de logs langs schieten tijdens het uitvoeren van flows. Als je dan je flow uitvoert zou je eventueel een foutmelding kunnen zien.

Ga ik direct even doen, maar lijkt nu wel te werken, is dit misschien een nieuwere versie (github) als in de appstore

**Comment by dannymertens** [comment]
> > Probeer eens athom app run in plaats van athom app install.
> > Dan zie je de logs langs schieten tijdens het uitvoeren van flows. Als je dan je flow uitvoert zou je eventueel een foutmelding kunnen zien.
> 
> Ga ik direct even doen, maar lijkt nu wel te werken, is dit misschien een nieuwere versie (github) als in de appstore



> Probeer eens athom app run in plaats van athom app install.
> 
> Dan zie je de logs langs schieten tijdens het uitvoeren van flows. Als je dan je flow uitvoert zou je eventueel een foutmelding kunnen zien.

OK gedaan en tja gaat nu wel goed, zal eens proberen, vrees dat ik dus ben uit getest? als ik nog iets kan doen om de andere mensen te helpen dan hoor ik het graag, maar hier lijkt het nu gewoon te werken. 

![image](https://user-images.githubusercontent.com/46963011/55472821-5577f800-560d-11e9-881d-84ce945e6afd.png)

**Comment by jordenc** [comment]
Goed om te horen dat het nu werkt. Het ziet er ook goed uit in de screenshot. Wellicht was een restart genoeg. Ik zal eens nakijken of dat niet toevallig het probleem was.

Voor nu zal ik 'm sluiten!

Je kunt overigens het beste even ctrl+C drukken zodat de app niet meer draait, en opnieuw installeren vanuit de appstore (zodat je updates meepakt)

**Comment by dannymertens** [comment]
@jordenc moet ik verder terug iets verwijderen van mijn Homey of is alles gewoon prima zo en kan dit gewoon blijven staan, die debug optie op mijn Mac vindt ik wel handig dus die mag wel blijven staan wat mij betreft, of is dit een security issue?

**Comment by dannymertens** [comment]
> Goed om te horen dat het nu werkt. Het ziet er ook goed uit in de screenshot. Wellicht was een restart genoeg. Ik zal eens nakijken of dat niet toevallig het probleem was.
> 
> Voor nu zal ik 'm sluiten!
> 
> Je kunt overigens het beste even ctrl+C drukken zodat de app niet meer draait, en opnieuw installeren vanuit de appstore (zodat je updates meepakt)

OK dus eerst even deïnstalleren via de Homey en dan opnieuw de versie van de app store er op zetten? gaan we doen, bedankt voor je snelle hulp!

**Comment by dannymertens** [comment]
@jordenc Ok ik heb de app terug geïnstalleerd vanuit de app store, netjes geconfigureerd en test mail ging goed, daarna flow getest, eerst even kaartje verwijderd en terug aangemaakt om zeker te zijn, ging fout.

Daarna zoals jij dacht even de app herstart in Homey en ja hoor daarna werkte het wel, dus gewoon even na de configuratie herstarten lijkt het, misschien even toevoegen aan de beschrijving in de app store?

Wat me wel opvalt is dat de process indicator blijft draaien in de flow, zelfs na een succesvolle actie, is dit een probleem?

Tevens werken de line breaks niet, maar zal ik even nieuw issue voor aanmaken.

![image](https://user-images.githubusercontent.com/46963011/55473798-d46e3000-560f-11e9-9608-6b6ae82fe4ae.png)
![image](https://user-images.githubusercontent.com/46963011/55473822-e8b22d00-560f-11e9-93b7-41441e8efb1d.png)
