### ISSUE TITLE
Headers Show Up as Text in Homey Flow for Web (online version)

### ISSUE THREAD

**Issue by Jansrt** [jordenc/email-sender#13]
The headers 'Mail aan', 'Onderwerp' and 'Inhoud' show up 'Text' when using e-mail sender in the new Homey Flow for Web. 

I happens in all three cards that can be used.

See below for an example.

![schermafbeelding 2019-02-25 om 17 25 26 copy](https://user-images.githubusercontent.com/40427127/53352886-f2b38280-3923-11e9-8957-2ad783e594d4.png)

Can you fix this?

**Comment by jordenc** [comment]
This seems to be a bug in Homey flow - Not in this app. Please report to Athom. Same thing happens for the builtin "Send a push message" card.

**Comment by Jansrt** [comment]
Thank you for your help. I will report to Athom. I found out that there are more problems with using your app in Homey Flow for Web. That is why I did not get the tags working. By the way, I cannot use both cards (snapshot and e-mail) in one flow?

**Comment by jordenc** [comment]
Which problems were those?

No you can't use them in one flow. You have to make a snapshot first with the app or device that makes the snapshot, then that app or device will "trigger" a new flow when it's done. That new trigger card (in the "when" column) will have the correct image token on it.
