### ISSUE TITLE
Circle followed by Triangle

### ISSUE THREAD

**Issue by CyberSponk** [jordenc/email-sender#17]
Homey 2.5.1-rc3
MailSender 0.2.3

In a simple Flow to send a Text-Mail the Mail is sent when pressing "Test" but the Flow-Card shows a long Time a rotating Circle followed by an red Triangle with "Timeout'.

**Comment by AlexanderCP** [comment]
I have the same problem. I tried Gmail and 1 & 1. 
The testmail arrives, but the mail from the flow-card does not. "Timeout' is reported.

To clarify: The mail has worked for me, if I take as the sender the same e-mail address as for the recipient in the flow -although "timeout" was displayed in the test.
