### ISSUE TITLE
Email not send

### ISSUE THREAD

**Issue by chrisboer** [jordenc/email-sender#4]
"Invalid login: 535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8 https://support.google.com/mail/?p=BadCredentials 6sm44375590wjt.5 - gsmtp"

With Homey 1.0.3 and Gmail account an smtp.gmail.com with 587 as port.

Both tried with secure and unsecure sending same error

**Comment by jordenc** [comment]
"If you wish to send through Gmail SMTP servers, you first need to allow less secure apps on Gmail via https://www.google.com/settings/security/lesssecureapps

Use your complete @gmail.com mail address as the username, smtp.gmail.com as the SMTP server and SMTP port 587."

Please let me know if that still works.

**Comment by chrisboer** [comment]
Have it working on smtp where I don't need to login to with userid and password.

But I could not get it to work on gmail I already have lesssecureapps on because of IP cam

So Gmail still an issue

**Comment by jordenc** [comment]
You are right, I just tested with Gmail and I guess they have changed their routines so it now no longer works. I don't have a solution yet.

**Comment by Dijker** [comment]
Works for me now without any problem using the (gratis) G Suite.

**Comment by chrisboer** [comment]
my secure 587 mail don't work anymore with hotmail it works
