### ISSUE TITLE
[Feature Request] Make sending an email available through the WebAPI

### ISSUE THREAD

**Issue by bm480** [jordenc/email-sender#7]
I'm currently experimenting with HomeyScript and like to be able to send an email. As far as I know, it should be possible to call other apps using the WebAPI. However, the Email Sender app only exposes a testmail uri which can not be used to send real emails. It would be nice if the regular actions were callable through the WebAPI.

**Comment by jordenc** [comment]
I am updating the app to 0.2.1 which has support for this. Please try and let me know if it works! (App first has to be approved by Athom)
