### ISSUE TITLE
Not working. 

### ISSUE THREAD

**Issue by kapusticka** [jordenc/email-sender#9]
In Athom Homey v2 not working. Test giving me error: {"line":1,"column":2075,"sourceURL":"http://192.168.0.8/manager/webserver/assets/js/homey.js"}

**Comment by jordenc** [comment]
It's just the notice that doesn't work. The function works (except if your settings aren't correct), it just doesn't show the response from the mail server.

I am going to fix this soon when I have time.

**Comment by jordenc** [comment]
Version 0.2.3 has been submitted to appstore (not yet approved) which has a fix for this bug.
